on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TZ: Asia/Shanghai

jobs:
  prepare-matrix:
    runs-on: ubuntu-latest
    outputs:
      ids: ${{ steps.set-matrix.outputs.ids }}
    steps:
      - uses: actions/checkout@v4
      - id: set-matrix
        run: |
          count=64
          ids=$(jq -c -n --argjson n "$count" '[range(1; $n+1)]')
          echo "ids=$ids" >> $GITHUB_OUTPUT

  concurrent-jobs:
    needs: prepare-matrix
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        job_id: ${{ fromJson(needs.prepare-matrix.outputs.ids) }}
    steps:
      - uses: actions/checkout@v4

      - name: 运行
        run: |
          yarn
          npx puppeteer browsers install firefox
          yarn build && timeout -k 30s 300s yarn dev

          cp $GITHUB_STEP_SUMMARY step-summary
          truncate -s 0 $GITHUB_STEP_SUMMARY

      - name: 上传 step summary artifact
        if: always() && hashFiles('step-summary') != ''
        uses: actions/upload-artifact@v4
        with:
          name: step-summary-${{ matrix.job_id }}
          path: step-summary

      - name: 上传 images 文件夹
        if: always() && hashFiles('images/**') != ''
        uses: actions/upload-artifact@v4
        with:
          name: images-${{ matrix.job_id }}
          path: images/

  collect-summary:
    runs-on: ubuntu-latest
    needs: concurrent-jobs
    steps:
      - name: 下载所有 job 的 step summary
        uses: actions/download-artifact@v4
        with:
          path: summaries

      - name: 合并 step summary
        run: |
          # cat summaries/step-summary-*/* > $GITHUB_STEP_SUMMARY
          jq -s '.' summaries/step-summary-*/* > $GITHUB_STEP_SUMMARY
